import { MailboxListResponseSchema } from '@cloudflare-inbox/contracts/mailboxes'
import {
  ThreadDetailResponseSchema,
  ThreadListResponseSchema,
} from '@cloudflare-inbox/contracts/threads'

import type { InboxData } from './inbox-types'

const mailboxId = '019b08e0-1000-7000-8000-000000000001'
const threadOneId = '019b08e0-2000-7000-8000-000000000001'

const baseThreads = [
  {
    id: threadOneId,
    mailboxId,
    subject: 'Workspace migration timeline',
    preview: 'The final import finished cleanly. Could you confirm the cutover window?',
    participants: [{ address: 'maya.chen@example.test', displayName: 'Maya Chen' }],
    workflowState: 'needs_reply',
    archivedAt: null,
    lastMessageAt: '2026-08-01T02:42:00.000Z',
    lastMessageDirection: 'inbound',
    messageCount: 3,
    unreadCount: 1,
    attachmentCount: 1,
    tags: [{ name: 'priority' }],
  },
  {
    id: '019b08e0-2000-7000-8000-000000000002',
    mailboxId,
    subject: 'Invoice for July',
    preview: 'Your receipt and itemized invoice are attached for review.',
    participants: [{ address: 'billing@example.test', displayName: 'Example Billing' }],
    workflowState: 'resolved',
    archivedAt: null,
    lastMessageAt: '2026-08-01T01:18:00.000Z',
    lastMessageDirection: 'inbound',
    messageCount: 1,
    unreadCount: 0,
    attachmentCount: 1,
    tags: [],
  },
  {
    id: '019b08e0-2000-7000-8000-000000000003',
    mailboxId,
    subject: 'Deployment completed',
    preview: 'Production checks passed in every region.',
    participants: [{ address: 'builds@example.test', displayName: 'Build Monitor' }],
    workflowState: 'resolved',
    archivedAt: null,
    lastMessageAt: '2026-07-31T15:08:00.000Z',
    lastMessageDirection: 'inbound',
    messageCount: 4,
    unreadCount: 0,
    attachmentCount: 0,
    tags: [{ name: 'system' }],
  },
  {
    id: '019b08e0-2000-7000-8000-000000000004',
    mailboxId,
    subject: 'Partnership notes',
    preview: 'Thanks — we will share the revised outline after Monday.',
    participants: [{ address: 'jordan.lee@example.test', displayName: 'Jordan Lee' }],
    workflowState: 'waiting',
    archivedAt: null,
    lastMessageAt: '2026-07-31T09:15:00.000Z',
    lastMessageDirection: 'outbound',
    messageCount: 5,
    unreadCount: 0,
    attachmentCount: 2,
    tags: [],
  },
  {
    id: '019b08e0-2000-7000-8000-000000000005',
    mailboxId,
    subject: 'Email routing check',
    preview: 'Inbound delivery succeeded and the raw source is available.',
    participants: [{ address: 'routing@example.test', displayName: 'Route Worker' }],
    workflowState: 'needs_reply',
    archivedAt: null,
    lastMessageAt: '2026-07-30T23:40:00.000Z',
    lastMessageDirection: 'inbound',
    messageCount: 2,
    unreadCount: 2,
    attachmentCount: 0,
    tags: [],
  },
  {
    id: '019b08e0-2000-7000-8000-000000000006',
    mailboxId,
    subject: 'Access request resolved',
    preview: 'The temporary account has been closed as requested.',
    participants: [{ address: 'olivia.park@example.test', displayName: 'Olivia Park' }],
    workflowState: 'resolved',
    archivedAt: '2026-07-29T05:10:00.000Z',
    lastMessageAt: '2026-07-29T05:10:00.000Z',
    lastMessageDirection: 'outbound',
    messageCount: 3,
    unreadCount: 0,
    attachmentCount: 0,
    tags: [],
  },
] as const

export function createPreviewInboxData(): InboxData {
  const { mailboxes } = MailboxListResponseSchema.parse({
    mailboxes: [
      {
        id: mailboxId,
        address: 'support@example.test',
        forwardTo: 'owner@example.test',
        forwardHtml: true,
        renderHtml: false,
        senderAlias: 'Example Support',
        counts: { all: 18, unread: 3, needsReply: 4, sent: 9, archive: 7 },
        createdAt: '2026-01-05T03:00:00.000Z',
        updatedAt: '2026-08-01T02:42:00.000Z',
      },
    ],
  })
  const { items: threads } = ThreadListResponseSchema.parse({
    items: baseThreads,
    nextCursor: null,
  })
  const selectedThread = ThreadDetailResponseSchema.parse({
    thread: baseThreads[0],
    messages: [
      {
        id: '019b08e0-3000-7000-8000-000000000001',
        mailboxId,
        threadId: threadOneId,
        direction: 'inbound',
        internetMessageId: '<migration-1@example.test>',
        inReplyTo: null,
        from: { address: 'maya.chen@example.test', displayName: 'Maya Chen' },
        recipients: [
          {
            kind: 'to',
            position: 0,
            address: 'support@example.test',
            displayName: 'Example Support',
          },
          {
            kind: 'reply_to',
            position: 0,
            address: 'maya.chen@example.test',
            displayName: 'Maya Chen',
          },
        ],
        references: [],
        subject: 'Workspace migration timeline',
        preview: 'The final import finished cleanly.',
        textBody:
          'Hi team,\n\nThe final import finished cleanly. Could you confirm the cutover window still works for you?\n\nThanks,\nMaya',
        htmlBody: null,
        htmlPolicy: 'none',
        sentAt: '2026-07-31T08:20:00.000Z',
        receivedAt: '2026-07-31T08:20:01.000Z',
        readAt: '2026-07-31T08:26:00.000Z',
        sendState: 'not_applicable',
        forwardState: 'forwarded',
        failure: null,
        rawAvailable: true,
        rawSize: 18342,
        attachments: [],
      },
      {
        id: '019b08e0-3000-7000-8000-000000000002',
        mailboxId,
        threadId: threadOneId,
        direction: 'outbound',
        internetMessageId: '<migration-2@example.test>',
        inReplyTo: '<migration-1@example.test>',
        from: { address: 'support@example.test', displayName: 'Example Support' },
        recipients: [
          { kind: 'to', position: 0, address: 'maya.chen@example.test', displayName: 'Maya Chen' },
        ],
        references: ['<migration-1@example.test>'],
        subject: 'Re: Workspace migration timeline',
        preview: 'The 16:00 UTC cutover is still reserved.',
        textBody:
          'Hi Maya,\n\nThe 16:00 UTC cutover is still reserved. I attached the final checklist for your team.\n\nBest,\nExample Support',
        htmlBody: null,
        htmlPolicy: 'none',
        sentAt: '2026-07-31T09:04:00.000Z',
        receivedAt: null,
        readAt: null,
        sendState: 'sent',
        forwardState: 'not_applicable',
        failure: null,
        rawAvailable: true,
        rawSize: 24820,
        attachments: [
          {
            id: '019b08e0-4000-7000-8000-000000000001',
            ordinal: 0,
            filename: 'migration-checklist.pdf',
            mediaType: 'application/pdf',
            size: 148204,
            disposition: 'attachment',
            contentId: null,
          },
        ],
      },
      {
        id: '019b08e0-3000-7000-8000-000000000003',
        mailboxId,
        threadId: threadOneId,
        direction: 'inbound',
        internetMessageId: '<migration-3@example.test>',
        inReplyTo: '<migration-2@example.test>',
        from: { address: 'maya.chen@example.test', displayName: 'Maya Chen' },
        recipients: [
          {
            kind: 'to',
            position: 0,
            address: 'support@example.test',
            displayName: 'Example Support',
          },
          {
            kind: 'reply_to',
            position: 0,
            address: 'maya.chen@example.test',
            displayName: 'Maya Chen',
          },
        ],
        references: ['<migration-1@example.test>', '<migration-2@example.test>'],
        subject: 'Re: Workspace migration timeline',
        preview: 'Perfect. Please send the final confirmation after DNS settles.',
        textBody:
          'Perfect. Please send the final confirmation after DNS settles. We will keep the old route available until then.',
        htmlBody: null,
        htmlPolicy: 'none',
        sentAt: '2026-08-01T02:42:00.000Z',
        receivedAt: '2026-08-01T02:42:01.000Z',
        readAt: null,
        sendState: 'not_applicable',
        forwardState: 'forwarded',
        failure: null,
        rawAvailable: true,
        rawSize: 19642,
        attachments: [],
      },
    ],
  })

  return { mailboxes, threads, selectedThread, nextCursor: null }
}
